const ProjectImg = [
    {
        id:1,
        imgsrc:"./all/1.png"
    },
    {
        id:2,
        imgsrc:"./all/2.png"
    },
    {
        id:3,
        imgsrc:"./all/3.png"
    },
    {
        id:4,
        imgsrc:"./all/4.png"
    },
    {
        id:5,
        imgsrc:"./all/5.png"
    },
    {
        id:6,
        imgsrc:"./all/6.png"
    },
    {
        id:7,
        imgsrc:"./all/7.png"
    },
    {
        id:8,
        imgsrc:"./all/8.png"
    },
    {
        id:9,
        imgsrc:"./all/9.png"
    },
    {
        id:10,
        imgsrc:"./all/10.png"
    },
    {
        id:11,
        imgsrc:"./all/11.png"
    },
    {
        id:12,
        imgsrc:"./all/12.png"
    },
    {
        id:13,
        imgsrc:"./all/13.png"
    },
    {
        id:14,
        imgsrc:"./all/14.png"
    },
    {
        id:15,
        imgsrc:"./all/15.png"
    },
    {
        id:16,
        imgsrc:"./all/16.png"
    },
    {
        id:17,
        imgsrc:"./all/17.png"
    },
    {
        id:18,
        imgsrc:"./all/18.png"
    },
    {
        id:19,
        imgsrc:"./all/19.png"
    },
    {
        id:20,
        imgsrc:"./all/20.png"
    },
    {
        id:21,
        imgsrc:"./all/21.png"
    },
    {
        id:22,
        imgsrc:"./all/22.png"
    },
]

export default ProjectImg